### PR TITLE
Create python-app.yml

### PR DESCRIPTION
**Pull request by KorkaDiallo**
pipeline ci

### CODE REVIEW

**Comment by KorkaDiallo** [comment]
Add CI pipeline

**Review by MNIKIEMA — APPROVED** [review]
Nice

**Review by Alpha-DIALLO-2024 — APPROVED** [review]

**Comment by Alpha-DIALLO-2024** [comment]
Top

**Review by ISSOUF01 — APPROVED** [review]
ok

**Review by MNIKIEMA — APPROVED** [review]
OK

**Review by MNIKIEMA — APPROVED** [review]
OK

**Review by Alpha-DIALLO-2024 — APPROVED** [review]

**Comment by Alpha-DIALLO-2024** [comment]
ok

**Review by ISSOUF01 — APPROVED** [review]
ok

**Review by MNIKIEMA — APPROVED** [review]
Yes

**Review by ISSOUF01 — APPROVED** [review]
ok

**Review by ISSOUF01 — APPROVED** [review]
ok

**Review by MNIKIEMA — APPROVED** [review]
I am OK

**Pull request merged**
